require 'io/console'
require 'colorize'
require 'securerandom'
require 'yaml'
require 'pry'

require_relative 'custom_shell_prefix'
require_relative 'visual_mode'
require_relative 'builtins'
require_relative 'aliases'
